services:
  energiai-frontend:
    build: ./energiai-frontend
    container_name: energiai_frontend
    ports:
      - "80:80"
    networks:
      - energiai_net
    depends_on:
      - energiai-api

  energiai-api:
    build: ./energiai-api
    container_name: energiai_api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/energiai
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - energiai_net
    depends_on:
      - db

  db:
    image: mysql:9.7
    container_name: mysql_energiai
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:root}
      MYSQL_DATABASE: energiai
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - energiai_net

volumes:
  mysql_data:

networks:
  energiai_net: