server {
    listen 80;
    server_name energiai-frontend;

    root /usr/share/nginx/html;
    index index.html;

    # Servir archivos estáticos con caché de un año para mejorar el rendimiento
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, inmutable";
    }

    # rediregir todas las rutas al index.html para que el enrutador del frontend maneje la navegación
    location / {
        try_files $uri $uri/ /index.html;
    }


    # Prevenir el acceso a archivos ocultos (como .htaccess, .git, etc.)
    location ~ /\. {
        deny all;
    }
}